# pve2otelcol configuration

[global]
otlp-logger-name = pve2otelcol
otlp-exporter = grpc
otlp-grpc-url = http://localhost:4317
otlp-http-url = https://localhost:4318
otlp-tls-ca-file =
otlp-tls-cert-file =
otlp-tls-key-file =
otlp-compression = gzip
otlp-initial-interval = 2
otlp-max-interval = 10
otlp-max-elapsed-time = 30
otlp-timeout = 10000
otlp-grpc-reconnection-period = 10
otlp-batch-buffer-size = 1
otlp-batch-export-interval = 1
otlp-batch-max-batch-size = 512
refresh-interval = 10
cmd-retry-times = 5
cmd-retry-delay = 5
discovery-timeout = 10
capability-probe-timeout = 5
metrics-listen-address = 127.0.0.1:9221
cursor-dir = /var/lib/pve2otelcol/cursors
skip-lxcs = false
skip-pve = false
dry-run = false
verbose = false

[vms]
# IDs are comma-separated.
include =
exclude =
